<h1 style="text-align: center;">МАТРИЧНОЕ ПРЕОБРАЗОВАНИЕ ПРИЗНАКОВ НА ПРИМЕРЕ ЗАДАЧИ ОБЕЗЛИЧИВАНИЯ ДАННЫХ</h1>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Описание-проекта" data-toc-modified-id="Описание-проекта-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Описание проекта</a></span><ul class="toc-item"><li><span><a href="#Описание-данных" data-toc-modified-id="Описание-данных-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Описание данных</a></span></li><li><span><a href="#Постановка-задачи" data-toc-modified-id="Постановка-задачи-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Постановка задачи</a></span></li></ul></li><li><span><a href="#Импорт-библиотек,-описание-констант" data-toc-modified-id="Импорт-библиотек,-описание-констант-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Импорт библиотек, описание констант</a></span></li><li><span><a href="#Обзор-и-подготовка-данных" data-toc-modified-id="Обзор-и-подготовка-данных-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Обзор и подготовка данных</a></span><ul class="toc-item"><li><span><a href="#Переименование-столбцов" data-toc-modified-id="Переименование-столбцов-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Переименование столбцов</a></span></li><li><span><a href="#Корректировка-типов" data-toc-modified-id="Корректировка-типов-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Корректировка типов</a></span></li><li><span><a href="#Проверка" data-toc-modified-id="Проверка-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Проверка</a></span></li></ul></li><li><span><a href="#Умножение-на-матрицу" data-toc-modified-id="Умножение-на-матрицу-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Умножение на матрицу</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Признаки-без-шифрования" data-toc-modified-id="Признаки-без-шифрования-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Признаки без шифрования</a></span></li><li><span><a href="#Признаки-с-шифрованием" data-toc-modified-id="Признаки-с-шифрованием-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Признаки с шифрованием</a></span></li><li><span><a href="#Заключение" data-toc-modified-id="Заключение-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Заключение</a></span></li></ul></li><li><span><a href="#Выводы" data-toc-modified-id="Выводы-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Выводы</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

## Описание проекта 
Вам нужно защитить данные клиентов страховой компании «Хоть потоп». 
### Описание данных 
В вашем распоряжении данные клиентов.

**Признаки:**
 - `Пол` - пол застрахованного, 
 - `Возраст` - возраст застрахованного,
 - `Зарплата` - зарплата застрахованного,
 - `Члены семьи` - количество членов семьи.
 
**Целевой признак:**
 - `Страховые выплаты` - количество страховых выплат клиенту за последние 5 лет.
 
### Постановка задачи
Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы. 

**Важно!**
Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

**Ход решения:**
 - загрузите и изучите данные, 
 - покажите аналитически, изменится ли качество линейной регрессии при умножении признаков на обратимую матрицу,
 - сформулируйте и обоснуйте алгоритм преобразования данных для решения задачи,  
 - запрограммируйте алгоритм, применив матричные операции,
 - с помощью метрики `R2` покажите, что качество моделей `LinearRegression` не отличается до и после преобразования. 

## Импорт библиотек, описание констант

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
#фиксируем: 
# - параметр random state
SEED = 42
# - путь к файлам данных
PATH = '/datasets/insurance.csv'
# - целевой признак
TARGET = 'payments'

## Обзор и подготовка данных
Поместим данные в DataFrame. На примере нескольких строк оценим датасеты визульно. Посмотрим на общую информацию.

In [3]:
df = pd.read_csv(PATH)
display(df.sample(10))
df.info()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
4670    0     34.0   35500.0            1                  0
4163    1     27.0   50400.0            2                  0
2035    1     21.0   59200.0            1                  0
2766    1     35.0   32400.0            2                  0
1030    0     20.0   46100.0            1                  0
227     0     28.0   54300.0            1                  0
4605    0     29.0   46300.0            1                  0
1538    1     36.0   41900.0            5                  0
2428    0     29.0   43400.0            1                  0
4675    0     26.0   46800.0            1                  0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Типы данных, за исключением возраста, определены верно, данные интерпретированы корректно. Пропуски отсутствуют. Столбцы именованы в кириллице. 

### Переименование столбцов
Переименуем столбцы в `snake_case`, сохранив семантику.

In [4]:
df.columns = ['gender', 'age', 'salary', 'family', 'payments']

### Корректировка типов 
Приведем столбец `age` к целочисленному типу, предварительно убедившись, что значения кратны едиинице.

In [5]:
print('Уникальные значения стобца age:\n', df['age'].unique())

Уникальные значения стобца age:
 [41. 46. 29. 21. 28. 43. 39. 25. 36. 32. 38. 23. 40. 34. 26. 42. 27. 33.
 47. 30. 19. 31. 22. 20. 24. 18. 37. 48. 45. 44. 52. 49. 35. 56. 65. 55.
 57. 54. 50. 53. 51. 58. 59. 60. 61. 62.]


In [6]:
df = df.astype({'age' : 'int64'})

### Проверка
Посмотрим на результат преобразований. 

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   gender    5000 non-null   int64  
 1   age       5000 non-null   int64  
 2   salary    5000 non-null   float64
 3   family    5000 non-null   int64  
 4   payments  5000 non-null   int64  
dtypes: float64(1), int64(4)
memory usage: 195.4 KB


Преобразования прошли корректно.
## Умножение на матрицу
**ВОПРОС**

Изменится ли предсказательное качество линейной регрессии при умножении признаков на обратимую матрицу?      

**ОТВЕТ**

Не изменится (см. аналитическое доказательство ниже).

**ОБОСНОВАНИЕ**

Напомним основные зависимости для алгоритма линейной регрессии.

Вектор предсказаний: $a = Xw$

Весовой вектор: $w = (X^T X)^{-1}X^Ty$

Формулировка задачи обучения: $w = \arg\min_w MSE(Xw, y)$, где:
- $X$ — матрица признаков (нулевой столбец состоит из единиц),
- $y$ — вектор целевого признака,
- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Запишем матрицу преобразованных признаков в виде $X_{1} = XP$, где:
 - $X$ - матрица исходных признаков, 
 - $P$ - случайная обратимая матрица. 
 
Таким образом, вектор предсказаний: $a_{1} = X_{1}w_{1}$

А весовой вектор: $w_{1} = (X_{1}^T X_{1})^{-1} X_{1}^T y$

**Найдем зависимость $w_{1}(w)$:**

$$w_{1} = (X_{1}^T X_{1})^{-1} X_{1}^T y = ((XP)^T (XP))^{-1} (XP)^T y$$

Воспользовавшись свойствами матриц: $(AB)^{-1} = B^{-1}A^{-1}$, $(AB)^{T} = B^{T}A^{T}$ и $A(BC) = (AB)C$, получим следующее: 

$$w_{1} = (P^TX^TXP)^{-1}(XP)^Ty = P^{-1}(X^TX)^{-1}(P^T)^{-1}P^TX^Ty$$

Учитывая, что $AA^{-1} = A^{-1}A = E$ и $AE = EA = A$, получим следующее:

$$w_{1} = P^{-1}(X^TX)^{-1}EX^Ty = P^{-1}(X^TX)^{-1}X^Ty$$

При этом $w = (X^T X)^{-1}X^Ty$, следовательно: 

$$w_{1} = P^{-1}w$$

**Покажем, что $a = a_{1}$:**

$$a_{1} = X_{1}w_{1} = XPP^{-1}w = XEw = Xw = a$$ 

Векторы предсказаний равны для линейной регрессии с преобразованными ($X_{1}$) и исходными ($X$) признаками. Следовательно, преобразование признаков не влияет на качество модели.  
## Алгоритм преобразования
Обезличим признаки, умножив их на случайную обратимую матрицу.

**АЛГОРИТМ**
 - в качестве ключа шифрования подбираем обратимую (квадратную и невырожденную) матрицу $P$, состоящую из случайных чисел. Важно, чтобы ее размерность была согласована с матрицей признаков $X$, иначе операция умножения будет невозможна. Для нашего случая, это $P_{4x4}$;
 - получаем шифрованную версию признаков $X_{1}$ умножением матрицы признаков $X$ на ключ шифрования $P$;
 - формируем обучающую и тестовую выборки с зашифрованными признаками;
 - обучаем модель `LinearRegression` на зашифрованной обучающей выборке, замеряем качество (`R2`) на зашифрованной тестовой выборке.

**ОБОСНОВАНИЕ**

Умножив матрицу признаков $X_{mxn}$ на обратимую матрицу $P_{nxn}$, мы получим новую матрицу $X_{1mxn}$. Таким образом, мы обезличим признаковое пространство, сохранив его размерность. При этом обезличенные признаки однозначно зависимы от исходных. Т.е. нам доступно, как шифрование $X_{1mxn} = X_{mxn}P_{nxn}$, так и дешифрование $X_{mxn} = X_{1mxn}P_{nxn}^{-1}$ признаков без потери предсказательной способности модели, что показано ниже экспериметально.

## Проверка алгоритма
Определим следующие функции:

In [8]:
def encryption_key(size):
    """Возвращает ключ шифрования - 
    обратимую (квадратную, невырожденную) 
    матрицу заданного размера, заполненную 
    случайными целыми числами от 1 до 100
    АРГУМЕНТЫ:
    size -- размер ключа шифрования
    """
    result = None
    # инициализируем определитель
    det = 0
    # пока определитель равен нулю 
    while det == 0:
        # формируем случайную матрицу 
        result = np.random.randint(1, 100, (size, size))
        # считаем определитель 
        det = np.linalg.det(result)
    # определитель отличен от нуля, т.е. 
    # матрица невырожденная, при этом квадратная, 
    # следовательно, обратимая
    return result  

In [9]:
def encrypt(X):
    """Возвращает матрицу зашифрованных
    признаков и ключ шифрования
    АРГУМЕНТЫ:
    X -- признаки для шифрования
    """
    P = encryption_key(X.shape[1])
    return X @ P, P

Подготовим признаки и ключ шифрования. 

In [10]:
# вектор целевого признака
y = df[TARGET]
# исходная матрица признаков 
X = df.drop(TARGET, axis=1)
# зашифрованная матрица признаков
# и матрица - ключ шифрования
X1, P = encrypt(X.values)

Проверим преобразование признаков и ключ шифрования.

In [11]:
print('Ключ шифрования:\n', P)
pd.DataFrame(X1, columns=X.columns, index=X.index)

Ключ шифрования:
 [[45 23 12 25]
 [11 15 63  2]
 [52  6 18 53]
 [29 80 21 95]]


gender       age    salary     family
0     2579725.0  298318.0  895416.0  2629002.0
1     1976535.0  228770.0  686919.0  2014187.0
2     1092319.0  126435.0  379827.0  1113058.0
3     2168689.0  250675.0  751965.0  2210332.0
4     1357553.0  157043.0  471576.0  1383381.0
...         ...       ...       ...        ...
4995  1856766.0  214780.0  644406.0  1892346.0
4996  2725203.0  314990.0  945363.0  2777363.0
4997  1763078.0  203860.0  611502.0  1796930.0
4998  1700774.0  196793.0  590061.0  1733454.0
4999  2111582.0  244123.0  732597.0  2151976.0

[5000 rows x 4 columns]

Признаки обезличены, размер ключа шифрования (4х4) согласован с количесвом признаков.
### Признаки без шифрования
Сформируем обучающую и тестовую выборки. Проверим их размерность. 

In [12]:
X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size=0.25, random_state=SEED)
print('Размер выборок:',
     '\n - обучающая (признаки):', X_train.shape,
     '\n - обучающая (целевой признак):', y_train.shape,
     '\n - тестовая (признаки):', X_test.shape,
     '\n - тестовая (целевой признак):', y_test.shape,)

Размер выборок: 
 - обучающая (признаки): (3750, 4) 
 - обучающая (целевой признак): (3750,) 
 - тестовая (признаки): (1250, 4) 
 - тестовая (целевой признак): (1250,)


Выборки сформированы корректно.

Обучим модель `LinearRegression` и определим значение `R2` на тестовой выборке. 

In [13]:
lr = LinearRegression()
lr.fit(X_train, y_train)
a = lr.predict(X_test)
r2 = round(r2_score(y_test, a), 4)
print('R2 на данных без шифрования:', r2)

R2 на данных без шифрования: 0.4255


### Признаки с шифрованием
Сформируем обучающую и тестовую выборки для шифрованных данных. Проверим размерность выборок. 

In [14]:
X1_train, X1_test, y_train, y_test = \
train_test_split(X1, y, test_size=0.25, random_state=SEED)
print('Размер выборок:',
     '\n - обучающая (признаки):', X1_train.shape,
     '\n - обучающая (целевой признак):', y_train.shape,
     '\n - тестовая (признаки):', X1_test.shape,
     '\n - тестовая (целевой признак):', y_test.shape,)

Размер выборок: 
 - обучающая (признаки): (3750, 4) 
 - обучающая (целевой признак): (3750,) 
 - тестовая (признаки): (1250, 4) 
 - тестовая (целевой признак): (1250,)


Выборки сформированы корректно.

На зашифрованных данных обучим модель `LinearRegression` и определим значение `R2` на тестовой выборке. 

In [15]:
lr1 = LinearRegression()
lr1.fit(X1_train, y_train)
a1 = lr1.predict(X1_test)
r21 = round(r2_score(y_test, a1), 4)
print('R2 на данных с шифрованием:', r21)

R2 на данных с шифрованием: 0.4255


### Заключение
Сравним значение `R2` для исходных и обезличенных данных.

In [16]:
pd.DataFrame([r2, r21], columns=['R2'], index=['X (not encrypted)', 'X1 (encrypted)'])

R2
X (not encrypted)  0.4255
X1 (encrypted)     0.4255

Как видно, шифрование признаков не влияет на значение метрики `R2`. 

Проверим, выполняются ли зависимости:
$$w_{1} = P^{-1}w$$

In [17]:
w = lr.coef_
w1 = lr1.coef_
print('Весовые коэффициенты LinearRegression с шифрованием признаков:',
     '\n - полученные экспериментально:', w1, 
     '\n - полученные теоретически    :', np.linalg.inv(P) @ w)

Весовые коэффициенты LinearRegression с шифрованием признаков: 
 - полученные экспериментально: [ 1.42615180e-04  5.06301651e-06  5.42179115e-04 -3.24638440e-04] 
 - полученные теоретически    : [ 1.42615180e-04  5.06301651e-06  5.42179115e-04 -3.24638440e-04]


$$X = X_{1}P^{-1}$$

На примере пяти случайных строк, сравним дешифрованную (подвергшуюся прямому и обратному шифрованию) матрицу признаков...

In [18]:
X1_decrypted = pd.DataFrame(X1 @ np.linalg.inv(P), columns=X.columns, index=X.index)
X1_decrypted = X1_decrypted.round().astype({'gender' : 'int64', 
                                            'age' : 'int64',
                                            'family' : 'int64'})
X1_decrypted.sample(5, random_state=SEED)

gender  age   salary  family
1501       1   28  56100.0       0
2586       1   32  41900.0       2
2653       1   30  26300.0       0
1055       1   30  37300.0       2
705        0   44  30000.0       1

... с исходной (не шифровавшейся).

In [19]:
X.sample(5, random_state=SEED)

gender  age   salary  family
1501       1   28  56100.0       0
2586       1   32  41900.0       2
2653       1   30  26300.0       0
1055       1   30  37300.0       2
705        0   44  30000.0       1

$$a = a_{1}$$

In [21]:
# приводим векторы предсказаний к целочисленному типу
a_int = np.rint(a)
a1_int = np.rint(a1)
# сравниваем целочисленные векторы предсказаний
result = None
if np.array_equal(a_int, a1_int):
    result = 'ИДЕНТИЧНЫ'
else:
    result = 'НЕ ИДЕНТИЧНЫ'
    
print('Прогнозы LinearRegression без шифрования и с шифрованием {0}.'.format(result))    

Прогнозы LinearRegression без шифрования и с шифрованием ИДЕНТИЧНЫ.


Таким образом, зависимости, полученные аналитически ([см.4](#%D0%A3%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0-%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%83)), полностью подтверждаются экспериментально.
## Выводы
**В ходе загрузки и подготовки данных:**
 - переименованы столбцы ([см.3.1](#%D0%9F%D0%B5%D1%80%D0%B5%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%BE%D0%BB%D0%B1%D1%86%D0%BE%D0%B2)), 
 - скорректированы типы данных ([см.3.2](#%D0%9A%D0%BE%D1%80%D1%80%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D1%82%D0%B8%D0%BF%D0%BE%D0%B2)).
 
**В разделе "Умножение на матрицу"** ([см.4](#%D0%A3%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0-%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%83)): 
 - аналитически показано, что качество линейной регрессии не меняется при умножении признаков на обратимую матрицу;
 - сформулированы зависимости параметров линейной регрессии для исходных и преобразованных данных ($X_{1} = XP$, $w_{1} = P^{-1}w$, $a = a_{1}$)

**В разделе "Алгоритм преобразования"** предложен способ обезличивания данных путем умножения на обратимую матрицу ([см.5](#%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC-%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)).

**В ходе проверки алгоритма** ([см.6](#%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B0)) экспериментально показано:
 - значение метрики `R2` линейной регрессии неизменно при использовании незашифрованных и зашифрованных данных ([см.6.3](#%D0%97%D0%B0%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5));
 - зависимости $w_{1} = P^{-1}w$, $X = X_{1}P^{-1}$, $a = a_{1}$ выполняются ([см.6.3](#%D0%97%D0%B0%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5)).